# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Update /reeder

on:
  push:
    branches: [ "master", "github-pages" ]
  pull_request:
    branches: [ "master", "github-pages" ]
  repository_dispatch:
    types: [ "update_read" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Run 'rake update_read'
      run: bundle exec rake update_read
      env:
        PINBOARD_API_KEY: ${{ secrets.PINBOARD_API_KEY }}
    - name: Update _data/read.json
      uses: EndBug/add-and-commit@v9
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: '_data/read.json'

        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default: github_actor
        default_author: github_actor

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Updating _data/read.json'

        # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
        # - ignore -> errors will be logged but the step won't fail
        # - exitImmediately -> the action will stop right away, and the step will fail
        # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
        # Default: ignore
        pathspec_error_handling: ignore
